# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Global
destination: ../ruhkopf-blog-deploy

# Site settings
title: Patrick Ruhkopf - Blog
description: > # this means to ignore newlines until "baseurl:"
  My thoughts on programming, application design and (someday) photography. 
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "http://ruhkopf.name" # the base hostname & protocol for your site
twitter_username: serenehead
github_username:  serenehead

# Build settings
markdown: kramdown

# Plugins
gems: [jekyll-picture-tag]

# Picture settings
picture:
  source: "assets/images/_fullsize"
  output: "assets/images/generated"
  markup: "picture"
  presets:
    default:
      ppi: [1, 2]
      attr:
        class: "picture"
        itemprop: "image"
      source_medium:
        media: "(min-width: 40em)"
        width: "600"
      source_default: 
        width: "300"
    small:
      ppi: [1, 2]
      attr:
        class: "picture-small"
        itemprop: "image"
      source_medium:
        media: "(min-width: 40em)"
        width: "300"
      source_default: 
        width: "150"
    big:
      ppi: [1, 2]
      attr:
        class: "picture-big"
        itemprop: "image"
      source_medium:
        media: "(min-width: 40em)"
        width: "740"
      source_default: 
        width: "370"